+*/* 
    UNIVERSIDAD MARIANO GALVEZ DE GUATEMALA
    INGENIERIA EN SISTEMAS
            Víctor Gabriel Madrid Barrios		1690-22-4772
            Juan Marcos Castro Tolentino		1690-22-18398
			Rudy Jaser Samuel Castellanos Lopez	1690-22-9776

*/
alter session set "_oracle_script"=true;

--DDL
CREATE USER ProyectoF IDENTIFIED BY toor
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON SYSTEM;

-- PRIVILEGIOS DDL
GRANT CREATE SESSION TO ProyectoF;
GRANT CREATE TABLE TO ProyectoF;
GRANT CREATE PROCEDURE TO ProyectoF;
GRANT CREATE TRIGGER TO ProyectoF;

--PRIVILEGIOS DML
GRANT INSERT ANY TABLE TO ProyectoF;
GRANT DELETE ANY TABLE TO ProyectoF;
GRANT UPDATE ANY TABLE TO ProyectoF;
GRANT SELECT ANY TABLE TO ProyectoF;

GRANT CREATE TYPE TO ProyectoF;
GRANT CREATE SEQUENCE TO ProyectoF;
GRANT CREATE VIEW TO ProyectoF;

